//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolEntities : DbContext
    {
        public SchoolEntities()
            : base("name=SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseInstructor> CourseInstructors { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<OfficeAssignment> OfficeAssignments { get; set; }
        public virtual DbSet<OnlineCourse> OnlineCourses { get; set; }
        public virtual DbSet<OnsiteCourse> OnsiteCourses { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<StudentGrade> StudentGrades { get; set; }
    
        public virtual ObjectResult<GetCoursesOfInstructor_Result> GetCoursesOfInstructor(string firstName, string lastName)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCoursesOfInstructor_Result>("GetCoursesOfInstructor", firstNameParameter, lastNameParameter);
        }
    
        public virtual ObjectResult<GetInstructorPerformanceReport_Result> GetInstructorPerformanceReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInstructorPerformanceReport_Result>("GetInstructorPerformanceReport");
        }
    
        public virtual ObjectResult<GetStudentPerformanceReportOfCourse_Result> GetStudentPerformanceReportOfCourse(string courseName)
        {
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentPerformanceReportOfCourse_Result>("GetStudentPerformanceReportOfCourse", courseNameParameter);
        }
    
        public virtual ObjectResult<GetStudentsInDepartment_Result> GetStudentsInDepartment(string deptName)
        {
            var deptNameParameter = deptName != null ?
                new ObjectParameter("DeptName", deptName) :
                new ObjectParameter("DeptName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsInDepartment_Result>("GetStudentsInDepartment", deptNameParameter);
        }
    
        public virtual ObjectResult<InstructorPerformanceReport_Result> InstructorPerformanceReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InstructorPerformanceReport_Result>("InstructorPerformanceReport");
        }
    }
}
